### PR TITLE
Use sink peak instead of sink state to determine if audio is playing.…

### PR DESCRIPTION
**Pull request by Tank-Missile**
… Remove source check as sink input check also detects record streams (at least through my testing).

### CODE REVIEW

**Comment by carlocastoldi** [comment]
Is there any reason why this PR is not taken into consideration? After applying it to my setup I can say it works like charm!
I would really love if it was at least discussed.

**Comment by WhyNotHugo** [comment]
I've nothing against merging it. Would just need to update merge conflicts.

Does this provide less false-positives for you, BTW?

**Comment by carlocastoldi** [comment]
> _Does this provide less false-positives for you, BTW?_
> @WhyNotHugo 

After almost 1 day I've been trying out this patch I can say it doesn't provide much false-positives (none at all, in fact).

On the other hand, tho, it provides some false-negatives. Which is not good. Maybe even worse than a false-positive :\

From my understanding it dependeds on the output I use. When I was using my bluetooth headphones it worked like charm. If I was using front or back jack I had false-negatives

Knowing that I tried fixing it by changing `sink_source`'s value in `sink_peak = pulseaudio.get_peak_sample(sink_source, 0.1)` to something else and, once I found the right sink, I managed to make it work

P.S. btw i have to say that i thought that `caffeine-ng` didn't work with only audio playing. That was because my distro (Manjaro/Arch) must have packaged it wrongly. I am now using the git version and I found no false-postives/negatives for the time being! :)

**Comment by carlocastoldi** [comment]
I made this easy script that "emulates" the patch:
```python
from pulsectl import Pulse

with Pulse() as pulseaudio:
    for sink in pulseaudio.sink_input_list():
        print("sink: ", sink)
        sink_source = pulseaudio.sink_info(sink.sink).monitor_source
        print("\tsink_source: ", sink_source)
        for i in range(0,10):
            print("\ti =",i)
            sink_peak = pulseaudio.get_peak_sample(i, 0.1)
            print("\t\tsink_peak: ", sink_peak)
            if sink_peak > 0:
                print("\t\tsink_proplist: ",sink.proplist.get('media.role'))
```

As you can see when i select from GUI (KDE) to use my bluetooth output, `pulseaudio.sink_info(sink.sink).monitor_source` guesses the right `sink_source` (see `output 1`).
This doesn't happen when I select internal audio analog stereo (see `output 2`).

<details> 
  <summary><code>output 1</code></summary>
   <pre><code>sink:  index=2, mute=0, name='Spotify'
        sink_source:  7
        i = 0
                sink_peak:  0
        i = 1
                sink_peak:  0.374151349067688
                sink_proplist:  music
        i = 2
                sink_peak:  0
        i = 3
                sink_peak:  0
        i = 4
                sink_peak:  0
        i = 5
                sink_peak:  0
        i = 6
                sink_peak:  0
        i = 7
                sink_peak:  0.027252197265625
                sink_proplist:  music
        i = 8
                sink_peak:  0
        i = 9
                sink_peak:  0</code></pre>
</details>
<details> 
  <summary><code>output 2</code></summary>
   <pre><code>sink:  index=2, mute=0, name='Spotify'
        sink_source:  0
        i = 0
                sink_peak:  0
        i = 1
                sink_peak:  0.16610205173492432
                sink_proplist:  music
        i = 2
                sink_peak:  0
        i = 3
                sink_peak:  0
        i = 4
                sink_peak:  0
        i = 5
                sink_peak:  0
        i = 6
                sink_peak:  0
        i = 7
                sink_peak:  0
        i = 8
                sink_peak:  0
        i = 9
                sink_peak:  0
</code></pre>
</details>



NOTE: I don't know why in `output 1` sink 1 appears to be active :man_shrugging:

**Comment by WhyNotHugo** [comment]
You testing would seem to indicate that this PR would work (and even be a bit more reliable).

> NOTE: I don't know why in output 1 sink 1 appears to be active man_shrugging

This confuses me too. What does `pavucontrol` show?

**Comment by WhyNotHugo** [comment]
Oh, also, if you mute you system (not a single app), do you find that any of both interfere? (sorry, can't tests this myself right now).

**Comment by carlocastoldi** [comment]
> You testing would seem to indicate that this PR would work (and even be a bit more reliable).

Why so? Since I posted here I used the git version (installed from [AUR](https://aur.archlinux.org/packages/caffeine-ng-git/)) and found not problems. It works flawlessly when I switch between the outputs as well.
The only problem I can see (but I don't care too much) is that if the audio is muted, then it is not detected and thus it remains inhibited.

> > NOTE: I don't know why in output 1 sink 1 appears to be active man_shrugging
> 
> This confuses me too. What does `pavucontrol` show?

I'm stupid, sorry. That `sink 1` was my mic. I keep always keep it connected, thus it always finds some activity on the relative sink (and rightfully it doesn't consider it).

However this means that the internal audio is not detected at all? I find that hard to believe, but as the things are now it is confirmed:
* `pulseaudio.sink_info(sink.sink).monitor_source` does not automatically detect it
* I tried to extend the range to ` for i in range(0,100)` and I still can't find an active sink when internal audio is selected

**Comment by carlocastoldi** [comment]
> Oh, also, if you mute you system (not a single app), do you find that any of both interfere? (sorry, can't tests this myself right now).

what do you mean by "any of both"?

By the way, when I mute the system, my sample script detects no `sink_peak` at all on the bluetooth sink i was using

**Comment by WhyNotHugo** [comment]
`pulseaudio.get_peak_sample` returns peaks for _sources_ (e.g.: microphones or sink-monitors).

You look all sources 0 thru 10, but really, you should just use all the `pulseaudio.sink_info(sink.sink).monitor_source` values:

```python
from pulsectl import Pulse

with Pulse() as pulseaudio:
    for sink in pulseaudio.sink_input_list():
        print("sink: ", sink)
        sink_source = pulseaudio.sink_info(sink.sink).monitor_source
        print("\tsink_source: ", sink_source)

        sink_peak = pulseaudio.get_peak_sample(sink_source, 0.1)
        print("\tsink_peak: ", sink_peak)
        if sink_peak > 0:
            print("\tsink_proplist: ", sink.proplist.get("media.role"))
```

However, in my case `get_peak_sample` always returns 0. I'm not entirely sure why, but I'm sure I'm using _something_ here wrong.

### Cleaner approach

I think a much cleaner approach is to determine if the stream is `mute` or `corked` (corked means "playback is stopped / paused").

This has provided much more reliable results for me (and I actually better understand what it does):

```python
from pulsectl import Pulse

with Pulse() as pulseaudio:
    for sink in pulseaudio.sink_input_list():
        print("sink:", sink)

        print("\tsink.mute:", sink.mute)
        print("\tsink.corked:", sink.corked)  # Corking equals stopping playback.
        print("\tsink_proplist.media.role:", sink.proplist.get("media.role"))

        sink_source = pulseaudio.sink_info(sink.sink).monitor_source
        sink_source_info = pulseaudio.source_info(sink_source)
        sink_source_peak = pulseaudio.get_peak_sample(sink_source, 0.5)

        print("\tsink_source:", sink_source, sink_source_info.description)
        print("\tsink_source_peak:", sink_source_peak)  # Always returns 0 for me...?
```

Does this yield good results for you too?

**Comment by carlocastoldi** [comment]
> However, in my case `get_peak_sample` always returns 0. I'm not entirely sure why, but I'm sure I'm using _something_ here wrong.

Yes, that was exactly the problem I had. I was of the impression that `get_peak_sample()` couldn't **always** get the volume of the active source. To be sure that it wasn't a case of `pulseaudio.sink_info(sink.sink).monitor_source` returning the wrong source, i looped on the first 10 sources (then i tried the first 100) trying to find other active ones.

Problem is that now my system works and i cannot reproduce the bug: `get_peak_sample()` is always returning the right value for me. But at least I'm "happy" it wasn't my fault but you also came upon the same problem.

> I think a much cleaner approach is to determine if the stream is `mute` or `corked`. [...] Does this yield good results for you too?

That is a great idea, good job! It even appears to be a faster check to me

The downside of this approach, after just a minute or two of testing, is that it doesn't detect when the whole system (not a single app) is muted. If you think that that's not a big of a deal, then I guess we could go further with this. Otherwise we should try finding out what's that _something_ we are using wrong in `get_peak_sample()`.

Additionally: I don't know how it behaves with record-streams. @Tank-Missile said that in his approach _"sink input check also detects record streams (at least through my testing)"_

**Comment by carlocastoldi** [comment]
> The downside of this approach, after just a minute or two of testing, is that it doesn't detect when the whole system (not a single app) is muted.

I just found that we could just use `pulseaudio.sink_info(sink.sink).mute`. It returns `1` if muted, `0` otherwise!

With that resolved I'd say we should be ready for an easy patch. What do you want to do? Should we open another PR?

**Comment by WhyNotHugo** [comment]
Right! A stream may be unmuted but it's sink is muted, so that final check covers that.

I think there's nothing more to be explored here, so if you want to draft a PR, we can move that forward.

**Comment by Tank-Missile** [comment]
I was not aware mute status could be checked that way.  You can ask the python-pulse-control dev about any confusion you're having using the library. I suppose I'll just close this PR since it's outdated and no longer necessary.

**Pull request closed without merging**
