### PR TITLE
"Process Name" set translatable

### PR DESCRIPTION
**Pull request by kelebek333**
"Process Name" set translatable

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Thanks!

**Comment by kelebek333** [comment]
Not at all.

Additionally, I added Caffeine-ng to my PPA for Ubuntu bionic, focal and hirsute base. 

https://launchpad.net/~kelebek333/+archive/ubuntu/tools

Thus, it can be easily installed to Ubuntu base with the following commands. 

```
sudo add-apt-repository ppa:kelebek333/tools
sudo apt-get update
sudo apt install caffeine-ng
```

**Comment by WhyNotHugo** [comment]
Nice. If you're going to keep this up to date, do you want to make a reference to this in the README?

**Comment by kelebek333** [comment]
> Nice. If you're going to keep this up to date, do you want to make a reference to this in the README?

A few weeks can be behind but I try to keep it up to date. 

> (or do you mind if I add one?)

Yes, You can add. If You want, I can prepare a separate PPA repository.

**Pull request merged**
